spring:
  application:
    name: scheduleclass
  datasource:
    url: jdbc:postgresql://db:5432/SCHEDULECLASS_DB   # 'db' é o nome do serviço no docker-compose
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
server:
  port: 8080

logging:
  file:
    path: /app/logs
